### ISSUE TITLE
Unclear link.

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#10]
Confirmation box for User Registration has an almost invisible link:

Registration request has been sent. You'll receive an e-mail as soon as the request has been accepted and handled. In the mean time, please carefully read our _Introduction Guide to UiL OTS Labs_. For questions regarding the registration, please contact the reservation system manager (tel. 06-22736073).

_Introduction Guide to UiL OTS Labs_ is a link but it's blue. Mayble underline it?

**Comment by mhkuu** [comment]
http://getbootstrap.com/components/#alerts-links maybe?

**Comment by AJdeMooij** [comment]
Using alert type "success" (which is green) instead of the blue "info" also works =)
Fixed
