### ISSUE TITLE
When succesfull logged in page should switch to main page

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#12]
Observed: after logging in you remain at the Login page. It would be nice if there would be an automatic switch to the main page.

**Comment by AJdeMooij** [comment]
Intended behaviour. If you click the link in the "You are not logged in" notification, you get redirected back to the page you came from after a succesful login. If you click the login link from the menu, it leaves you on the login page, because it was a manual navigation action.
