### ISSUE TITLE
Adding Facility Group

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#13]
When creating a new Facility Group with a single facility I read '_Huh. Problem with database._' or something along those lines. If I press 'Save' again I get the notification the facility group already exists.

**Comment by AJdeMooij** [comment]
Turned out to be an error with the order of arguments that got introduced with updating from the mysql module to the mysqli module. Fixed
