### ISSUE TITLE
Login as user (via !<username>) broken

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#22]
Login in as another user via !<username> and master password does not function correctly. It keeps login me out for each page/step.

**Comment by AJdeMooij** [comment]
Only for Solis users, because no hash of their password is stored in the db. Working on fix

**Comment by AJdeMooij** [comment]
Authentication with solis users works once through LDAP and after that with tokens. No token was created if the !<username> method was used. This is now fixed

**Comment by mhkuu** [comment]
It's nice that it works again, but I want to stress that (1) we should refrain from using this option (people should reserve things themselves) and (2) this master password is a serious security flaw. It would be much better if there would be an admin role. I'll create a new issue for this.
