### ISSUE TITLE
Remove master password, create admin role

### ISSUE THREAD

**Issue by mhkuu** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#25]
Not sure about priority, but I feel the master password is a security flaw and we should have an admin profile or use the manager-role for this. 

This would however mean that the functionality for logging in as another user would be removed. This might have to be replaced by something else.

**Comment by AJdeMooij** [comment]
* Get rid of admin password. Use Solis id to login on backend and frontend. Flag "admin" determines priviliges
* Change "pretend to be user" functionality. Only available to logged in Admins, requires entering admin credentials again
* Send feedback data to user if admin makes changes in their name (similar to the reservation e-mail fris admins get. Just a notification)
* E-mail that is sent to FRIS should indicate if admin made changes
* Log admin actions, either in a log, or in the DB

**Comment by mhkuu** [comment]
That seems a complete list, maybe we should talk about this in the next lab meeting. I feel that the "impersonating another user" functionality should go all together, but maybe someone who actually uses the system on a daily basis (i.e. not me) thinks otherwise :-)

**Comment by cpavanrun** [comment]
Iris en ik hebben het in het verleden vaak gebruikt. Soms zijn gebruikers
te moeilijk om het aan ze te vragen om te veranderen...
