### ISSUE TITLE
Reserveringen verdwijnen 

### ISSUE THREAD

**Issue by cpavanrun** [UiL-OTS-labs-backoffice/Facility-Reservation-and-Information-System-FRIS-#36]
Aldus Iris (zie ook mail):

> er gaat iets helemaal niet goed in fris: als je een reservering hebt
> staan voor eerder in de week, en je maakt een nieuwe reservering, dan
> wordt de reservering voor eerder in de week weggegooid.
> 
> ik heb dat nu twee keer zien gebeuren, de eerste keer dacht ik dat ik
> misschien per ongeluk iets fout had aangeklikt, maar dat is niet zo (je
> kunt die oudere reserveringen niet eens aanklikken). reserveringen van
> mij die ten onrechte verdwenen zijn zijn:
> 
> - K.05 EEGlabmeeting afgelopen maandag 12-13h
> - tutorial met emily afgelopen dinsdag 14-15h in K.12
> 
> het gebeurt zo te zien alleen in de weken die je op dat moment open hebt
> staan bij het reserveren, dus het is niet zo dat ALLE reserveringen uit
> het verleden verdwijnen.

**Comment by AJdeMooij** [comment]
Als het goed is solved met de laatste hotfix, maar er zit nog wel een fout in de code die alleen op de server manifesteert. Dat heb ik geworkaround, maar moet nog even gefixt worden
